---
- name: enable node_exporter
  service:
    name: node_exporter
    state: started
    enabled: true

- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted
    