- name: Update apt-cache 
  apt: 
    update_cache=yes

- name: Install Apache
  apt: 
    name=apache2 
    state=latest

- name: Create custom document root
  file:
    path={{ apache_document_root }}
    state=directory
    owner=www-data
    group=www-data

- name: set up HTML file
  copy:
    src=/var/www/html/index.html
    dest={{ apache_document_root }}/index.html
    owner=www-data
    group=www-data
    mode=0755
    remote_src=yes

- name: Set up Apache virtual host file
  template: 
    src=vhost.tpl
    dest=/etc/apache2/sites-available/000-default.conf
  notify: restart apache


- name: UFW - Allow 80 connections
  community.general.ufw:
    rule: allow
    port: 80
