---
# Handler to enable and start SSH service
- name: enable prometheus
  service:
    name: prometheus
    state: started
    enabled: true


# Handler to restart SSH service
- name: restart prometheus
  service:
    name: prometheus
    state: restarted
    